Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox"
  config.vm.provision :shell, path: "scripts/myscript.sh"
  config.vm.network "public_network"
  config.vm.hostname = "centos7"
end